### ISSUE TITLE
Exclude `log` directory from analysis

### ISSUE THREAD

**Issue by itsderek23** [hyperloop-rails/powerstation#1]
It looks like the script greps everything inside the current directory. 

Some directories should likely be excluded by default, like the `/log` directory, which frequently contains large files that don't have application code.

**Comment by chadwilken** [comment]
@itsderek23 I just copied into the directories I cared about `app` and so on and then ran it in isolation per directory

**Comment by hyperloop-rails** [comment]
You can now use the java version which takes in the folder as the parameter 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
